"""
src/generation/document_generator.py — Document Generator for Maharashtra Legal Document Generation.

Assembles the final legal document draft by:
  1. Prepending a document header (pipeline variant, LLM model, cache version, run ID, disclaimer)
  2. Mapping LLM output to template slots (preserving structural order)
  3. Running citation verification
  4. Appending a citation index

Requirements: 4.2, 4.3, 4.5, 4.6, 5.1, 5.2, 5.3, 5.4, 5.5, 13.1, 13.2, 13.3, 13.4, 13.5
"""
from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field

from src.generation.citation_verifier import (
    Citation,
    CitationVerificationResult,
    verify_citations,
)
from src.generation.template_mapper import (
    Template,
    TemplateRegistry,
    TemplateSlot,
)
from config.settings import settings

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Document header template
# ---------------------------------------------------------------------------

_HEADER_TEMPLATE = """\
GENERATED BY: Maharashtra Legal Document Generation System
Pipeline: {pipeline_variant} | Model: {llm_model} | Cache/Corpus: {cache_version}
Run ID: {run_id}
DISCLAIMER: This document is system-generated and requires review by a qualified legal professional.
{hallucination_flag}"""

_HIGH_HALLUCINATION_FLAG = "WARNING: HIGH HALLUCINATION RISK — More than 10% of clauses could not be grounded."

# Citation index header
_CITATION_INDEX_HEADER = "\n\n--- CITATION INDEX ---\n"

# Indian Legal Citation Standard format
_CITATION_FORMAT = "[{act_name}, {year}] Section {section}, [{court_or_legislature}], [{judgment_year}]"

# Regex to strip template slot markers like [PARTIES_CLAUSE], [OPERATIVE_CLAUSE_1]
_SLOT_MARKER_RE = re.compile(r"\[[A-Z][A-Z_]*(?:_\d+)?\]\n?")

# Regex to detect unfilled slot placeholders that survived generation.
# Matches bare uppercase tokens like [PARTIES_CLAUSE], [SCHEDULE], [ATTESTATION]
# but NOT citation markers like [Transfer of Property Act, 1882] or [UNGROUNDED...].
_UNFILLED_SLOT_RE = re.compile(r"\[([A-Z][A-Z_]*(?:_\d+)?)\]")

# Regex to strip markdown bold/italic markers
_MD_BOLD_RE = re.compile(r"\*\*(.+?)\*\*", re.DOTALL)
_MD_ITALIC_RE = re.compile(r"\*(.+?)\*", re.DOTALL)


def _clean_llm_output(text: str) -> str:
    """
    Clean raw LLM output before assembly:
      - Remove template slot markers like [PARTIES_CLAUSE], [OPERATIVE_CLAUSE_1]
      - Strip markdown bold (**text** -> text) and italic (*text* -> text)
      - Replace rupee symbol with Rs. (Helvetica/PDF-safe)
    """
    text = _SLOT_MARKER_RE.sub("", text)
    text = _MD_BOLD_RE.sub(r"\1", text)
    text = _MD_ITALIC_RE.sub(r"\1", text)
    text = text.replace("\u20b9", "Rs.")
    return text.strip()


# Slot content extraction: look for numbered sections or keyword-based sections
_SECTION_PATTERNS = {
    "PARTIES_CLAUSE": re.compile(r"(?:PARTIES|THIS\s+DEED|THIS\s+AGREEMENT)[^\n]*\n(.*?)(?=\n[A-Z]{3,}|\Z)", re.DOTALL | re.IGNORECASE),
    "RECITALS": re.compile(r"(?:RECITALS?|WHEREAS)[^\n]*\n(.*?)(?=\n[A-Z]{3,}|\Z)", re.DOTALL | re.IGNORECASE),
    "SCHEDULE": re.compile(r"(?:SCHEDULE)[^\n]*\n(.*?)(?=\n[A-Z]{3,}|\Z)", re.DOTALL | re.IGNORECASE),
    "ATTESTATION": re.compile(r"(?:ATTESTATION|IN\s+WITNESS|SIGNED)[^\n]*\n(.*?)(?=\n[A-Z]{3,}|\Z)", re.DOTALL | re.IGNORECASE),
}


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class GeneratedDocument:
    content: str                    # full assembled document text
    header: str
    body: str
    citation_index: str
    citations: list[Citation]
    ungrounded_clauses: list[int]
    high_hallucination_risk: bool
    run_id: str
    underline_ranges: list[tuple[int, int]] = field(default_factory=list)
    unfilled_slots: list[str] = field(default_factory=list)  # slot names left incomplete by LLM
    doc_type: str = ""              # e.g. "sale_deed" — used by evaluator
    pipeline_variant: str = "CAG"  # pipeline that produced this document


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _build_header(
    pipeline_variant: str,
    llm_model: str,
    cache_version: str,
    run_id: str,
    high_hallucination_risk: bool,
) -> str:
    """Build the document header string."""
    hallucination_flag = _HIGH_HALLUCINATION_FLAG if high_hallucination_risk else ""
    return _HEADER_TEMPLATE.format(
        pipeline_variant=pipeline_variant,
        llm_model=llm_model,
        cache_version=cache_version,
        run_id=run_id,
        hallucination_flag=hallucination_flag,
    ).rstrip()


def _format_citation(citation: Citation) -> str:
    """Format a Citation per Indian Legal Citation Standard."""
    judgment_year = citation.judgment_year if citation.judgment_year else citation.year
    return _CITATION_FORMAT.format(
        act_name=citation.act_name,
        year=citation.year,
        section=citation.section,
        court_or_legislature=citation.court_or_legislature,
        judgment_year=judgment_year,
    )


def _build_citation_index(citations: list[Citation]) -> str:
    """
    Build the citation index appended to every document.
    Lists all cited sources with full bibliographic details and clause numbers.
    """
    if not citations:
        return _CITATION_INDEX_HEADER + "(No citations found in this document.)\n"

    lines: list[str] = [_CITATION_INDEX_HEADER]
    for i, citation in enumerate(citations, start=1):
        formatted = _format_citation(citation)
        clause_refs = ", ".join(str(c + 1) for c in citation.clause_numbers) if citation.clause_numbers else "N/A"
        lines.append(f"[{i}] {formatted}")
        lines.append(f"    Cited in clause(s): {clause_refs}")
    lines.append("")
    return "\n".join(lines)


def _extract_slot_content(llm_output: str, slot: TemplateSlot) -> str:
    """
    Extract content from LLM output that corresponds to a given template slot.

    Strategy:
      1. Try pattern-based extraction for known slot types
      2. Fall back to splitting the output into sections by position
    """
    slot_name = slot.name.upper()

    # Try known section patterns
    for key, pattern in _SECTION_PATTERNS.items():
        if key in slot_name:
            m = pattern.search(llm_output)
            if m:
                return m.group(1).strip()

    # For OPERATIVE_CLAUSE_N, extract numbered clauses
    operative_match = re.match(r"OPERATIVE_CLAUSE_(\d+)", slot_name)
    if operative_match:
        clause_num = int(operative_match.group(1))
        # Find numbered clauses in the output
        numbered_clauses = re.findall(
            r"(?:^|\n)\s*" + str(clause_num) + r"\.\s+(.+?)(?=\n\s*\d+\.|\Z)",
            llm_output,
            re.DOTALL,
        )
        if numbered_clauses:
            return numbered_clauses[0].strip()

    # Fallback: return a portion of the output based on slot position
    lines = [l for l in llm_output.splitlines() if l.strip()]
    if not lines:
        return ""

    # Divide output evenly among slots (rough heuristic)
    return ""  # Will be filled by the body assembly


def _map_llm_to_template(llm_output: str, template: Template) -> str:
    """
    Map LLM output to template slots, preserving structural order.
    Marathi sections are inserted verbatim at their positions.

    The LLM is already instructed to produce content for every slot in the
    correct order (via the slot-injection prompt). So the primary job here is:
      1. Return the cleaned LLM output as the document body.
      2. Prepend any Marathi sections at their declared positions.

    We do NOT re-inject slot name tokens — that was the source of the
    [PARTIES_CLAUSE — SECTION INCOMPLETE] ghost markers in the output.
    """
    body = llm_output  # already cleaned by _clean_llm_output before this call

    # If there are Marathi sections, insert them at the top (position 0)
    # before the English body. In practice Phase 1 templates have no Marathi
    # sections, so this is a no-op for the current document types.
    if template.marathi_sections:
        marathi_parts = [
            ms.text for ms in sorted(template.marathi_sections, key=lambda s: s.position)
        ]
        body = "\n\n".join(marathi_parts) + "\n\n" + body

    return body


def _validate_no_unfilled_slots(content: str) -> list[str]:
    """
    Scan generated content for unfilled template slot placeholders.

    Returns a list of slot names that are still present as bare tokens
    (e.g. ["PARTIES_CLAUSE", "SCHEDULE"]).  An empty list means the
    document is clean.

    Exclusions — these are NOT slot placeholders:
      - Anything containing a comma or space (citation markers like
        [Transfer of Property Act, 1882])
      - UNGROUNDED, OLLAMA_UNAVAILABLE, GROQ_UNAVAILABLE, AGENT_TIMEOUT
        (system-inserted markers)
    """
    system_markers = {
        "UNGROUNDED", "OLLAMA_UNAVAILABLE", "GROQ_UNAVAILABLE", "AGENT_TIMEOUT",
    }
    unfilled: list[str] = []
    for m in _UNFILLED_SLOT_RE.finditer(content):
        token = m.group(1)
        if token in system_markers:
            continue
        unfilled.append(token)
    return list(dict.fromkeys(unfilled))  # deduplicate, preserve order


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_document(
    llm_output: str,
    template: Template | None,
    cache_or_chunks,            # LegalCache or list[Chunk]
    doc_type: str,
    pipeline_variant: str,
    llm_model: str,
    run_id: str,
    cache_version: str = "1.0.0",
) -> GeneratedDocument:
    """
    Assemble the final legal document from LLM output.

    Steps:
      1. Get template (from registry or default)
      2. Map LLM output to template slots
      3. Verify citations against cache
      4. Build header (with hallucination flag if needed)
      5. Build citation index
      6. Assemble full document

    Args:
        llm_output:        Raw text from the LLM.
        template:          Template to use (or None to use registry/default).
        cache_or_chunks:   LegalCache or list of Chunk objects for citation verification.
        doc_type:          Document type string, e.g. "sale_deed".
        pipeline_variant:  e.g. "CAG", "Dense RAG", "Hybrid RAG", "Agentic RAG".
        llm_model:         LLM model name/version string.
        run_id:            UUID run identifier.
        cache_version:     Version string for the cache/corpus.

    Returns:
        GeneratedDocument with all assembled fields.
    """
    # Step 1: Resolve template
    if template is None:
        registry = TemplateRegistry()
        template = registry.get_template(doc_type)

    # Clean LLM output: strip slot markers, markdown, fix rupee symbol
    llm_output = _clean_llm_output(llm_output)

    # Step 2: Map LLM output to template slots
    body = _map_llm_to_template(llm_output, template)

    # Phase 1.5: Citation formatting (gated by feature flag)
    if settings.enable_citation_formatting:
        try:
            from src.generation.citation_formatter import (
                collect_citations,
                assign_reference_numbers,
                replace_markers,
                build_citation_index,
                normalize_citation_key,
            )
            body, citation_markers = collect_citations(body)
            citation_map = assign_reference_numbers(citation_markers)
            body = replace_markers(body, citation_map)
            phase15_citation_index = build_citation_index(citation_markers)
        except Exception as exc:
            logger.warning("Citation formatting failed, continuing without it: %s", exc)
            phase15_citation_index = None
    else:
        phase15_citation_index = None

    # Step 2a: Post-generation slot validation — detect any unfilled placeholders
    # that the LLM left as bare tokens (e.g. [PARTIES_CLAUSE], [SCHEDULE]).
    unfilled_slots = _validate_no_unfilled_slots(body)
    if unfilled_slots:
        logger.warning(
            "run_id=%s doc_type=%s: %d unfilled slot(s) detected after generation: %s. "
            "These sections will be flagged in the output.",
            run_id, doc_type, len(unfilled_slots), unfilled_slots,
        )
        # Replace each bare slot token with a visible review marker so the
        # reviewer knows exactly which sections need manual attention.
        for slot_name in unfilled_slots:
            body = body.replace(
                f"[{slot_name}]",
                f"[{slot_name} — SECTION INCOMPLETE, MANUAL DRAFTING REQUIRED]",
            )

    # Step 3: Verify citations
    # Handle both LegalCache and list[Chunk] inputs
    verification: CitationVerificationResult = _verify_against_source(body, cache_or_chunks)

    # Use verified text (with UNGROUNDED markers inserted)
    verified_body = verification.verified_text

    # Step 3a: Normalize any LLM underline markers out of the user-facing text
    # while preserving exact ranges for DOCX/PDF exporters.
    underline_ranges: list[tuple[int, int]] = []
    try:
        from src.generation.formatting_engine import parse_underline_markers
        verified_body, underline_ranges = parse_underline_markers(verified_body)
    except Exception as exc:
        logger.warning("Underline marker parsing failed, falling back to plain text: %s", exc)

    # Step 4: Build header
    header = _build_header(
        pipeline_variant=pipeline_variant,
        llm_model=llm_model,
        cache_version=cache_version,
        run_id=run_id,
        high_hallucination_risk=verification.high_hallucination_risk,
    )

    # Step 5: Build citation index — include all citations (grounded + ungrounded)
    all_citations = verification.grounded_citations + verification.ungrounded_citations
    citation_index = _build_citation_index(all_citations)

    # Use Phase 1.5 citation index if available
    if phase15_citation_index is not None:
        citation_index = phase15_citation_index

    # Step 6: Assemble full document
    content = f"{header}\n\n{verified_body}{citation_index}"

    # Collect ungrounded clause indices
    ungrounded_clauses = [
        c.clause_numbers[0] if c.clause_numbers else 0
        for c in verification.ungrounded_citations
    ]

    return GeneratedDocument(
        content=content,
        header=header,
        body=verified_body,
        underline_ranges=underline_ranges,
        citation_index=citation_index,
        citations=verification.grounded_citations,
        ungrounded_clauses=ungrounded_clauses,
        high_hallucination_risk=verification.high_hallucination_risk,
        run_id=run_id,
        unfilled_slots=unfilled_slots,
        doc_type=doc_type,
        pipeline_variant=pipeline_variant,
    )


def _verify_against_source(text: str, cache_or_chunks) -> CitationVerificationResult:
    """
    Dispatch citation verification to the appropriate verifier based on
    whether we have a LegalCache or a list of Chunk objects.
    """
    # Check if it's a LegalCache (has .documents attribute)
    if hasattr(cache_or_chunks, "documents"):
        return verify_citations(text, cache_or_chunks)

    # It's a list of Chunks — wrap in a minimal cache-like object
    if isinstance(cache_or_chunks, list):
        cache_wrapper = _ChunkListWrapper(cache_or_chunks)
        return verify_citations(text, cache_wrapper)

    # Fallback: no cache available, treat all citations as ungrounded
    logger.warning("No cache or chunks provided for citation verification.")
    cache_wrapper = _ChunkListWrapper([])
    return verify_citations(text, cache_wrapper)


class _ChunkListWrapper:
    """
    Minimal wrapper to make a list of Chunk objects look like a LegalCache
    for citation verification purposes.
    """

    def __init__(self, chunks: list) -> None:
        self.documents = [_ChunkAsEntry(c) for c in chunks]


class _ChunkAsEntry:
    """Adapts a Chunk to look like a CacheEntry (has .name attribute)."""

    def __init__(self, chunk) -> None:
        # Chunk has metadata.statute_reference or text
        if hasattr(chunk, "metadata") and hasattr(chunk.metadata, "statute_reference"):
            self.name = chunk.metadata.statute_reference
        elif hasattr(chunk, "text"):
            self.name = chunk.text[:80]
        else:
            self.name = str(chunk)
